### ISSUE TITLE
Create a working sample for prototyping pipelines and processes

### ISSUE THREAD

**Issue by augustog** [augustog/redi-p2-ws19-nf#2]
## Why
To make it easier to build working pipelines and analyses, it helps to work with a reduced dataset. 
Conclusions must be taken from the full dataset, but writing the analyses by trial and error is faster with a sample

## What to do
- Load full dataset in memory
- Select a sample of 100 movies using the `.sample(100)` method on a list of unique movie ids
- Filter all records to only include ratings for those movies
- Store the sample using your chosen format under `data/processed`

### Technical Notes
- The `sample` function call users a random number generator to choose movie ID's
- To ensure the code can run predictably, it is suggested to provide the `sample` method with an integer value for `random_state` argument

[Documentation for Sample method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html)

## Definition of Done
- A sample of all the ratings for a random selection of 100 movies is stored in this repository

**Comment by Javid912** [comment]
I Have made the file of 100 Film 
 https://drive.google.com/file/d/1maB2xmBbGPC2lXmR1erEcEI-2VbDTwO_/view?usp=sharing
